apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: docker.io/library/nextcloud:27
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nextcloud-data
          mountPath: /var/www/html
        env:
        - name: MYSQL_HOST
          value: "10.0.10.219"
        - name: MYSQL_USER
          value: "nextcloud"
        - name: MYSQL_DATABASE
          value: "nextcloud"
        - name: MYSQL_PASSWORD
          value: "WelcomeFolks123#!"
        - name: NEXTCLOUD_ADMIN_USER
          value: "ncadmin"
        - name: NEXTCLOUD_ADMIN_PASSWORD
          value: "WelcomeFolks123#!"
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: "130.162.48.8"
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud